name: Deploy to Netlify

on:
  push:
    branches:
      - master   # or "main" if your branch is main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build project
      - name: Build project
        run: npm run build

      # Step 5: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: ./build   # for React; use ./dist for Vue/Angular
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
